swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "swagger"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

#### ------- route config region --------
host: "192.168.1.251:5556"
basePath: "/"
#### endregion

schemes:
- "http"


#### ------- tags region ----------------
tags:

- name: 'luckyDraw'
  description: "抽奖"

paths:
  /common/spLogin:
    post:
      tags:
        - luckyDraw
      summary: 小程序登录
      description: code必选；encryptedData，iv授权之后传
      parameters:
        - name: code
          type: string
          in: formData
          required: true
        - name: encryptedData
          type: string
          in: formData
        - name: iv
          type: string
          in: formData
      responses:
        200:
          description: successful
          schema:
            type: object

#### endregion

definitions:
  emptyObject:
    type: 'object'

security:
  - bearerAuth: []         # use the same name as above

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"